# Generated by Django 3.2 on 2022-07-21 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('full_name', models.CharField(max_length=300)),
                ('email_id', models.CharField(max_length=300)),
                ('subject', models.CharField(max_length=300)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_type', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('year', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images/programming_projects/')),
                ('summary', models.TextField()),
                ('primary_button_text', models.CharField(blank=True, max_length=300, null=True)),
                ('primary_link', models.CharField(blank=True, max_length=300, null=True)),
                ('secondary_button_text', models.CharField(blank=True, max_length=300, null=True)),
                ('secondary_link', models.CharField(blank=True, max_length=300, null=True)),
                ('python', models.BooleanField(blank=True, null=True)),
                ('bootstrap', models.BooleanField(blank=True, null=True)),
                ('figma', models.BooleanField(blank=True, null=True)),
                ('html', models.BooleanField(blank=True, null=True)),
                ('js', models.BooleanField(blank=True, null=True)),
                ('react', models.BooleanField(blank=True, null=True)),
                ('scss', models.BooleanField(blank=True, null=True)),
                ('github', models.BooleanField(blank=True, null=True)),
            ],
        ),
    ]
