# Generated by Django 3.2 on 2022-07-11 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('full_name', models.CharField(max_length=300)),
                ('email_id', models.CharField(max_length=300)),
                ('subject', models.CharField(max_length=300)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProgrammingProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('year', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images/programming_projects/')),
                ('summary', models.TextField(blank=True, null=True)),
                ('link', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
