# Generated by Django 3.2 on 2022-07-12 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
