# Generated by Django 3.2 on 2022-07-11 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProgrammingProject',
            new_name='Project',
        ),
    ]
