# Generated by Django 3.2 on 2022-06-26 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmingproject',
            name='link',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
