# Generated by Django 3.2 on 2022-06-27 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_programmingproject_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmingproject',
            name='company',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
