# Generated by Django 3.2 on 2022-06-27 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_programmingproject_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmingproject',
            name='year',
            field=models.CharField(default=2021, max_length=200),
            preserve_default=False,
        ),
    ]
